--------------------------------------------------------
--  Arquivo criado - Sexta-feira-Agosto-28-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence SEQ_AUD
--------------------------------------------------------

   CREATE SEQUENCE  "AUDITORIA"."SEQ_AUD"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table AUDITORIA
--------------------------------------------------------

  CREATE TABLE "AUDITORIA"."AUDITORIA" 
   (	"AUD_ID" NUMBER(6,0), 
	"AUD_TABELA" VARCHAR2(30 BYTE), 
	"AUD_OPERACAO" CHAR(1 BYTE), 
	"AUD_HIST_ID" NUMBER(10,0), 
	"AUD_COLUNA" VARCHAR2(30 BYTE), 
	"AUD_VALOR_ANTIGO" VARCHAR2(255 BYTE), 
	"AUD_VALOR_NOVO" VARCHAR2(255 BYTE), 
	"AUD_USU_BD" VARCHAR2(30 BYTE), 
	"AUD_USU_SO" VARCHAR2(255 BYTE), 
	"AUD_DATA" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  GRANT INSERT ON "AUDITORIA"."AUDITORIA" TO "VEI";
  GRANT SELECT ON "AUDITORIA"."AUDITORIA" TO "VEI";
REM INSERTING into AUDITORIA.AUDITORIA
SET DEFINE OFF;
Insert into AUDITORIA.AUDITORIA (AUD_ID,AUD_TABELA,AUD_OPERACAO,AUD_HIST_ID,AUD_COLUNA,AUD_VALOR_ANTIGO,AUD_VALOR_NOVO,AUD_USU_BD,AUD_USU_SO,AUD_DATA) values ('21','H_MANUTENCAO','D','456','HMAN_MOTIVO','ARREFECIMENTO',null,'VEI','Fatec',to_date('28/08/26','DD/MM/RR'));
--------------------------------------------------------
--  DDL for Index PK_AUD
--------------------------------------------------------

  CREATE UNIQUE INDEX "AUDITORIA"."PK_AUD" ON "AUDITORIA"."AUDITORIA" ("AUD_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_AUD
--------------------------------------------------------

  CREATE UNIQUE INDEX "AUDITORIA"."PK_AUD" ON "AUDITORIA"."AUDITORIA" ("AUD_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger TG_SEQ_AUD
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "AUDITORIA"."TG_SEQ_AUD" 
BEFORE INSERT ON AUDITORIA
FOR EACH ROW
BEGIN
    :NEW.AUD_ID := SEQ_AUD.NEXTVAL;
END;

/
ALTER TRIGGER "AUDITORIA"."TG_SEQ_AUD" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TG_SEQ_AUD
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "AUDITORIA"."TG_SEQ_AUD" 
BEFORE INSERT ON AUDITORIA
FOR EACH ROW
BEGIN
    :NEW.AUD_ID := SEQ_AUD.NEXTVAL;
END;

/
ALTER TRIGGER "AUDITORIA"."TG_SEQ_AUD" ENABLE;
--------------------------------------------------------
--  DDL for Procedure PROC_AUDITORIA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "AUDITORIA"."PROC_AUDITORIA" (
    P_AUD_TABELA IN VARCHAR,
    P_AUD_OPERACAO IN CHAR,
    P_AUD_HIST_ID IN NUMBER,
    P_AUD_COLUNA IN VARCHAR,
    P_AUD_VALOR_ANTIGO IN VARCHAR,
    P_AUD_VALOR_NOVO IN VARCHAR,
    P_AUD_USU_BD IN VARCHAR,
    P_AUD_USU_SO IN VARCHAR,
    P_AUD_DATA IN DATE
)
IS
BEGIN

    INSERT INTO AUDITORIA
    VALUES (
        NULL,
        P_AUD_TABELA,
        P_AUD_OPERACAO,
        P_AUD_HIST_ID,
        P_AUD_COLUNA,
        P_AUD_VALOR_ANTIGO,
        P_AUD_VALOR_NOVO,
        P_AUD_USU_BD,
        P_AUD_USU_SO,
        P_AUD_DATA
    );

END;

/

  GRANT EXECUTE ON "AUDITORIA"."PROC_AUDITORIA" TO "VEI";
--------------------------------------------------------
--  Constraints for Table AUDITORIA
--------------------------------------------------------

  ALTER TABLE "AUDITORIA"."AUDITORIA" ADD CONSTRAINT "PK_AUD" PRIMARY KEY ("AUD_ID")
  USING INDEX "AUDITORIA"."PK_AUD"  ENABLE;
