--------------------------------------------------------
--  Arquivo criado - Sexta-feira-Agosto-28-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for View VW_VIATURAS_DETALHES
--------------------------------------------------------

  CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "DW"."VW_VIATURAS_DETALHES" ("VIA_ID", "VIA_KILOMETRAGEM", "MDL_NOME", "MAR_NOME", "TIV_DESCRICAO", "STATUS_HISTORICO") AS 
  SELECT 
    V_UNION.ID AS VIA_ID,
    V_UNION.KM AS VIA_KILOMETRAGEM,
    M.MDL_NOME AS MDL_NOME,
    MA.MAR_NOME AS MAR_NOME,
    TV.TIV_DESCRICAO AS TIV_DESCRICAO,
    V_UNION.ACAO AS STATUS_HISTORICO
  FROM (
    -- União da tabela ativa de viaturas e histórico de viaturas
    SELECT 
        VIA_ID AS ID, 
        VIA_KILOMETRAGEM AS KM, 
        VIA_MDL_ID AS MDL_ID,
        'ATUAL' AS ACAO
    FROM VEI.VIATURA
    UNION ALL
    SELECT 
        HVIA_VIA_ID AS ID, 
        HVIA_KILOMETRAGEM AS KM, 
        HVIA_MDL_ID AS MDL_ID,
        HVIA_ACAO AS ACAO
    FROM VEI.H_VIATURA
  ) V_UNION
  -- Liga ao modelo
  LEFT JOIN VEI.MODELO M       ON V_UNION.MDL_ID = M.MDL_ID
  -- Liga a marca (através do modelo)
  LEFT JOIN VEI.MARCA MA       ON M.MDL_MAR_ID = MA.MAR_ID
  -- Liga ao tipo de veículo (através do modelo)
  LEFT JOIN VEI.TIPO_VEICULO TV ON M.MDL_TIV_ID = TV.TIV_ID
;
--------------------------------------------------------
--  DDL for Materialized View MV_ESTATISTICAS_MANUTENCAO
--------------------------------------------------------

  CREATE MATERIALIZED VIEW "DW"."MV_ESTATISTICAS_MANUTENCAO" ("MARCA", "TOTAL_VEICULOS", "QTD_MANUTENCOES", "QTD_ACOES_CORRETIVAS", "MEDIA_KM_FROTA", "PCT_VEICULOS_DA_MARCA")
  SEGMENT CREATION IMMEDIATE
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
  BUILD IMMEDIATE
  USING INDEX 
  REFRESH FORCE ON DEMAND
  USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE ON QUERY COMPUTATION DISABLE QUERY REWRITE
  AS SELECT
    MA.MAR_NOME AS MARCA,
    COUNT(DISTINCT V.VIA_ID) AS TOTAL_VEICULOS,
    COUNT(M.MAN_ID) AS QTD_MANUTENCOES,
    COUNT(A.ACO_ID) AS QTD_ACOES_CORRETIVAS,
    ROUND(AVG(V.VIA_KILOMETRAGEM), 2) AS MEDIA_KM_FROTA,
    ROUND((COUNT(DISTINCT V.VIA_ID) * 100) / (SELECT COUNT(*) FROM VEI.VIATURA), 2) AS PCT_VEICULOS_DA_MARCA
  FROM VEI.MARCA MA
  JOIN VEI.MODELO MOD ON MA.MAR_ID = MOD.MDL_MAR_ID
  JOIN VEI.VIATURA V  ON MOD.MDL_ID = V.VIA_MDL_ID
  LEFT JOIN VEI.MANUTENCAO M ON V.VIA_ID = M.MAN_VIA_ID
  LEFT JOIN VEI.ACOES A      ON M.MAN_ID = A.ACO_MAN_ID
  GROUP BY MA.MAR_NOME;

   COMMENT ON MATERIALIZED VIEW "DW"."MV_ESTATISTICAS_MANUTENCAO"  IS 'Análise estatística de manutenções e frota por marca de veículo';
REM INSERTING into DW.MV_ESTATISTICAS_MANUTENCAO
SET DEFINE OFF;
Insert into DW.MV_ESTATISTICAS_MANUTENCAO (MARCA,TOTAL_VEICULOS,QTD_MANUTENCOES,QTD_ACOES_CORRETIVAS,MEDIA_KM_FROTA,PCT_VEICULOS_DA_MARCA) values ('CHEVROLET','2','213','212','197139','22,22');
Insert into DW.MV_ESTATISTICAS_MANUTENCAO (MARCA,TOTAL_VEICULOS,QTD_MANUTENCOES,QTD_ACOES_CORRETIVAS,MEDIA_KM_FROTA,PCT_VEICULOS_DA_MARCA) values ('RENAULT','2','72','71','154722,64','22,22');
Insert into DW.MV_ESTATISTICAS_MANUTENCAO (MARCA,TOTAL_VEICULOS,QTD_MANUTENCOES,QTD_ACOES_CORRETIVAS,MEDIA_KM_FROTA,PCT_VEICULOS_DA_MARCA) values ('VOLKSWAGEN','2','50','49','97166','22,22');
Insert into DW.MV_ESTATISTICAS_MANUTENCAO (MARCA,TOTAL_VEICULOS,QTD_MANUTENCOES,QTD_ACOES_CORRETIVAS,MEDIA_KM_FROTA,PCT_VEICULOS_DA_MARCA) values ('FORD','1','12','12','114178','11,11');
Insert into DW.MV_ESTATISTICAS_MANUTENCAO (MARCA,TOTAL_VEICULOS,QTD_MANUTENCOES,QTD_ACOES_CORRETIVAS,MEDIA_KM_FROTA,PCT_VEICULOS_DA_MARCA) values ('HONDA','1','17','17','40416','11,11');
Insert into DW.MV_ESTATISTICAS_MANUTENCAO (MARCA,TOTAL_VEICULOS,QTD_MANUTENCOES,QTD_ACOES_CORRETIVAS,MEDIA_KM_FROTA,PCT_VEICULOS_DA_MARCA) values ('YAMAHA','1','25','25','39117','11,11');
REM INSERTING into DW.VW_VIATURAS_DETALHES
SET DEFINE OFF;
Insert into DW.VW_VIATURAS_DETALHES (VIA_ID,VIA_KILOMETRAGEM,MDL_NOME,MAR_NOME,TIV_DESCRICAO,STATUS_HISTORICO) values ('106478','154743','DUSTER','RENAULT','CARRO','ATUAL');
Insert into DW.VW_VIATURAS_DETALHES (VIA_ID,VIA_KILOMETRAGEM,MDL_NOME,MAR_NOME,TIV_DESCRICAO,STATUS_HISTORICO) values ('106479','114178','RANGER','FORD','CARRO','ATUAL');
Insert into DW.VW_VIATURAS_DETALHES (VIA_ID,VIA_KILOMETRAGEM,MDL_NOME,MAR_NOME,TIV_DESCRICAO,STATUS_HISTORICO) values ('106482','197139','SPIN','CHEVROLET','CARRO','ATUAL');
Insert into DW.VW_VIATURAS_DETALHES (VIA_ID,VIA_KILOMETRAGEM,MDL_NOME,MAR_NOME,TIV_DESCRICAO,STATUS_HISTORICO) values ('106483','97166','GOL','VOLKSWAGEN','CARRO','ATUAL');
Insert into DW.VW_VIATURAS_DETALHES (VIA_ID,VIA_KILOMETRAGEM,MDL_NOME,MAR_NOME,TIV_DESCRICAO,STATUS_HISTORICO) values ('106480','40416','XRE','HONDA','MOTO','ATUAL');
Insert into DW.VW_VIATURAS_DETALHES (VIA_ID,VIA_KILOMETRAGEM,MDL_NOME,MAR_NOME,TIV_DESCRICAO,STATUS_HISTORICO) values ('106481','39117','LANDER','YAMAHA','MOTO','ATUAL');
Insert into DW.VW_VIATURAS_DETALHES (VIA_ID,VIA_KILOMETRAGEM,MDL_NOME,MAR_NOME,TIV_DESCRICAO,STATUS_HISTORICO) values ('7','197139','SPIN','CHEVROLET','CARRO','ATUAL');
Insert into DW.VW_VIATURAS_DETALHES (VIA_ID,VIA_KILOMETRAGEM,MDL_NOME,MAR_NOME,TIV_DESCRICAO,STATUS_HISTORICO) values ('8','153277','DUSTER','RENAULT','CARRO','ATUAL');
Insert into DW.VW_VIATURAS_DETALHES (VIA_ID,VIA_KILOMETRAGEM,MDL_NOME,MAR_NOME,TIV_DESCRICAO,STATUS_HISTORICO) values ('9','97166','GOL','VOLKSWAGEN','CARRO','ATUAL');
Insert into DW.VW_VIATURAS_DETALHES (VIA_ID,VIA_KILOMETRAGEM,MDL_NOME,MAR_NOME,TIV_DESCRICAO,STATUS_HISTORICO) values ('2','39117',null,null,null,'DELETE');
Insert into DW.VW_VIATURAS_DETALHES (VIA_ID,VIA_KILOMETRAGEM,MDL_NOME,MAR_NOME,TIV_DESCRICAO,STATUS_HISTORICO) values ('1','39117',null,null,null,'DELETE');
Insert into DW.VW_VIATURAS_DETALHES (VIA_ID,VIA_KILOMETRAGEM,MDL_NOME,MAR_NOME,TIV_DESCRICAO,STATUS_HISTORICO) values ('3','180439',null,null,null,'DELETE');
Insert into DW.VW_VIATURAS_DETALHES (VIA_ID,VIA_KILOMETRAGEM,MDL_NOME,MAR_NOME,TIV_DESCRICAO,STATUS_HISTORICO) values ('5','81203',null,null,null,'DELETE');
Insert into DW.VW_VIATURAS_DETALHES (VIA_ID,VIA_KILOMETRAGEM,MDL_NOME,MAR_NOME,TIV_DESCRICAO,STATUS_HISTORICO) values ('6','77142',null,null,null,'DELETE');
Insert into DW.VW_VIATURAS_DETALHES (VIA_ID,VIA_KILOMETRAGEM,MDL_NOME,MAR_NOME,TIV_DESCRICAO,STATUS_HISTORICO) values ('4','118010',null,null,null,'DELETE');
